<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: your_service.proto

namespace Example;

require_once('google/api/annotations.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class StringMessage extends \Google\Protobuf\Internal\Message
{
    private $value = '';

    public function getValue()
    {
        return $this->value;
    }

    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0ac7010a12796f75725f736572766963652e70726f746f12076578616d70" .
    "6c651a1c676f6f676c652f6170692f616e6e6f746174696f6e732e70726f" .
    "746f221e0a0d537472696e674d657373616765120d0a0576616c75651801" .
    "2001280932620a0b596f75725365727669636512530a044563686f12162e" .
    "6578616d706c652e537472696e674d6573736167651a162e6578616d706c" .
    "652e537472696e674d657373616765221b82d3e493021522102f76312f65" .
    "78616d706c652f6563686f3a012a620670726f746f33"
));

